### ISSUE TITLE
style "install now" button

### ISSUE THREAD

**Issue by niccokunzmann** [CodersOS/create#1]
the index page has a big button for installation (green)
and a big button (gray) for testing the installation

**Comment by Axolodev** [comment]
Hello! I'd like to contribute here.
What can I do to help?

**Comment by niccokunzmann** [comment]
Hi, the index page https://codersos.github.io/create/ has an "install now" button at the bottom which is not styled. You can style it. But in general: if you notice something you wan to improve, you can create a pull-request for that. This is just an issue where I noticed that the button could use some styling to be more noticable.

@mortaldraw What would you like to work on?

**Comment by Axolodev** [comment]
@niccokunzmann Well, I can style up the whole index page, either using a front-end framework like bootstrap or without it, whichever you prefer.

**Comment by niccokunzmann** [comment]
Sure, you can do this. If you like, you can create small independent pull-requests, I will merge them. I am interested in what you will do. I am not so experienced with web design 👍 

I do not really care about the tool. Let's have fun developing this software :)

**Comment by mortaldraw** [comment]
Update: I am currently working on the page but don't know how to "compile" it
![image](https://cloud.githubusercontent.com/assets/2335145/23595222/d6b2e958-01e5-11e7-8c25-fdb89e247678.png)
This is what it looks like right now

**Comment by Axolodev** [comment]
Update. I am currently working on the index webpage. 

I added bootstrap and this is what it currently looks like:
![image](https://cloud.githubusercontent.com/assets/2335145/23595257/16abfe5a-01e6-11e7-927c-0f02f0c647be.png)
 
What do you think? and, how can I compile it?

**Comment by niccokunzmann** [comment]
Hi, cool.

**Comment by niccokunzmann** [comment]
@mortaldraw have a look here: https://github.com/CodersOS/create#development
I described a bit. If you like, you can also improve this as you go. If you have any questions, you can ask.

**Comment by niccokunzmann** [comment]
If you like, you can create a pull-request any time.

**Comment by Axolodev** [comment]
#18 Done styling.

**Comment by niccokunzmann** [comment]
This is more than I hoped for! Wonderful. If you like to do any additional changes, feel free:)
