### ISSUE TITLE
Github Logo not visible

### ISSUE THREAD

**Issue by niccokunzmann** [CodersOS/create#20]
The logo of the link to the github page is not visible on the main website.
Please make is visible.

Hint:
- use relative paths so that the logo is visible with a local jekyll run and a served website for github pages.

**Comment by edsonmendieta** [comment]
Hi nicco, 

I edited the 'src' attribute to use a relative path for the github icon like so:

`<span><img src="../assets/github_icon.png" style="height:20px" alt="">Visit our github!</span>`

Is that what you wanted?

I made the change on my fork of the repository and it seems to be working just fine.

Here's a screen shot I took while running the site locally:

![github-iconcreate](https://cloud.githubusercontent.com/assets/14797436/23686547/21951d86-035f-11e7-8398-9ca784208532.png)

**Comment by niccokunzmann** [comment]
@edsonmendieta Yes, this is excatly what I wanted. Would you like to create a pull-request?

**Comment by edsonmendieta** [comment]
Great, will do.

**Comment by niccokunzmann** [comment]
Currently, I do not see the logo. We use jekyll includes: https://jekyllrb.com/docs/templates/#includes
This means that _include is not the folder of the file.
What are your thoughts, @edsonmendieta?

**Comment by edsonmendieta** [comment]
@niccokunzmann Sorry about that nicco, I didn't know that about the jekyll includes folder. 

Removing the leading "`..`" so that the relative path is "`assets/github_icon.png`" seems to work just fine. 

@mortaldraw has it in his pull request.

**Comment by niccokunzmann** [comment]
@mortaldraw @edsonmendieta Thanks! No problem, no harm. I am here to learn. I hope, you can learn things here, too. I hope you have no negative feelings about this. I am happy you are here, we have a conversation and fun and find out new things :)
