### ISSUE TITLE
Github link on installing.html

### ISSUE THREAD

**Issue by niccokunzmann** [CodersOS/create#6]
As with index.html there should be a link to github for the installing.html file.

**Comment by Manish-Giri** [comment]
@niccokunzmann In the HTML files, where should the links be added?

**Comment by niccokunzmann** [comment]
If you use the waving octocat, you can put it in the top-right corner. Example: http://hpimakerklub.github.io/
I think, At the top or in the footer - It depends on what the design should be. You can decide it.

**Comment by Manish-Giri** [comment]
@niccokunzmann All right! Let me see what I can do. Thank You 👍

**Comment by niccokunzmann** [comment]
If you need help with anything, please let me know!

**Comment by niccokunzmann** [comment]
Resolved in #19. Thanks!
